name: Companion Module Checks

on:
  push:

jobs:
  check:
    name: Check module

    permissions:
      packages: read

    uses: bitfocus/actions/.github/workflows/module-checks.yaml@main
    with:
      # Attach the built package to the workflow run, so it can be downloaded and sideloaded for testing
      upload-artifact: true
