name: Companion Module Checks

on:
  push:

jobs:
  check:
    name: Check module

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/module-checks.yaml
    with:
      # Attach the built package to the workflow run, so it can be downloaded and sideloaded for testing
      upload-artifact: true
